// test/features/catalog/application/catalog_controller_test.dart
//
// GENERATED by skill 70 (Test Generation Agent) from CatalogController — an
// @riverpod AsyncNotifier (see skill 08's example_controller.dart).
//
// Method used (skill 70 §"per-type: controller"): read the controller + its
// State + repo interface, enumerate the state-machine transitions and every
// mutation, then assert each — loading→data, error path, and an optimistic
// mutation with COMMIT and ROLLBACK. Pattern is skill 08's ProviderContainer +
// mocktail; this file APPLIES it, it does not re-derive it.
//
// Each test maps to a row in the worked-example table in SKILL.md and is written
// to be mutation-survivable (#71): flip a branch in the controller and a test
// here goes red. Conventions: ../../../references/CONVENTIONS.md (§5, §6).

import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:riverpod/riverpod.dart';

// Source under test (illustrative paths for the template).
import 'package:my_app/core/error/result.dart'; // Result, Ok, Err, Failure, NetworkFailure
import 'package:my_app/features/catalog/application/catalog_controller.dart';
import 'package:my_app/features/catalog/application/catalog_state.dart';
import 'package:my_app/features/catalog/domain/catalog_repository.dart';

class MockCatalogRepository extends Mock implements CatalogRepository {}

void main() {
  late MockCatalogRepository repo;

  // Build a container with the repo overridden by the fake, auto-disposed.
  // Tests NEVER hit a real repository (CONVENTIONS §6).
  ProviderContainer makeContainer() {
    final container = ProviderContainer(
      overrides: [catalogRepositoryProvider.overrideWithValue(repo)],
    );
    addTearDown(container.dispose);
    return container;
  }

  const items = [
    CatalogItem(id: '1', title: 'Alpha'),
    CatalogItem(id: '2', title: 'Beta', isFavorite: true),
  ];

  setUp(() {
    repo = MockCatalogRepository();
  });

  // -------------------------------------------------------------------------
  // build() — the load state machine. One test per transition.
  // -------------------------------------------------------------------------
  group('CatalogController.build', () {
    test('loading → data when the repository returns Ok', () async {
      when(() => repo.fetchItems()).thenAnswer((_) async => const Ok(items));

      final container = makeContainer();

      // First synchronous read is AsyncLoading — proves the loading frame
      // exists (mutation: a controller that pre-fills data would fail this).
      expect(
        container.read(catalogControllerProvider),
        const AsyncLoading<CatalogState>(),
      );

      // `.future` awaits the build's Future → resolves to data.
      final state = await container.read(catalogControllerProvider.future);
      expect(state.items, items);
      expect(state.filter, CatalogFilter.all);
      expect(container.read(catalogControllerProvider).hasValue, isTrue);
      verify(() => repo.fetchItems()).called(1);
    });

    test('loading → error when the repository returns Err', () async {
      when(() => repo.fetchItems())
          .thenAnswer((_) async => const Err(NetworkFailure('offline')));

      final container = makeContainer();

      // The unwrapped Failure must surface as AsyncError — not be swallowed.
      await expectLater(
        container.read(catalogControllerProvider.future),
        throwsA(isA<NetworkFailure>()),
      );

      final async = container.read(catalogControllerProvider);
      expect(async.hasError, isTrue);
      expect(async.error, isA<NetworkFailure>());
    });

    test('empty: Ok([]) yields a value state with no visible items', () async {
      when(() => repo.fetchItems())
          .thenAnswer((_) async => const Ok(<CatalogItem>[]));

      final container = makeContainer();
      final state = await container.read(catalogControllerProvider.future);

      // Empty is DATA, not an error (mutation: treating [] as error fails here).
      expect(container.read(catalogControllerProvider).hasValue, isTrue);
      expect(state.items, isEmpty);
      expect(state.visibleItems, isEmpty);
    });
  });

  // -------------------------------------------------------------------------
  // toggleFavorite — an optimistic mutation. The two highest-value tests:
  // the optimistic COMMIT and the ROLLBACK on failure.
  // -------------------------------------------------------------------------
  group('CatalogController.toggleFavorite', () {
    setUpAll(() {
      // toggleFavorite uses `any()` on a String — primitive, no fallback needed,
      // but register one defensively for clarity if args become custom types.
      registerFallbackValue('');
    });

    test('optimistic commit: Ok updates state and persists once', () async {
      when(() => repo.fetchItems()).thenAnswer((_) async => const Ok(items));
      // Repo confirms the toggle, returning the updated item.
      when(() => repo.toggleFavorite('1')).thenAnswer(
        (_) async => const Ok(CatalogItem(id: '1', title: 'Alpha', isFavorite: true)),
      );

      final container = makeContainer();
      await container.read(catalogControllerProvider.future);

      await container
          .read(catalogControllerProvider.notifier)
          .toggleFavorite('1');

      final state = container.read(catalogControllerProvider).requireValue;
      final toggled = state.items.firstWhere((i) => i.id == '1');
      expect(toggled.isFavorite, isTrue); // committed
      expect(container.read(catalogControllerProvider).hasError, isFalse);
      verify(() => repo.toggleFavorite('1')).called(1);
    });

    test('rollback: Err restores the pre-toggle state and surfaces error',
        () async {
      when(() => repo.fetchItems()).thenAnswer((_) async => const Ok(items));
      // The persist fails — the optimistic change must be rolled back.
      when(() => repo.toggleFavorite('1'))
          .thenAnswer((_) async => const Err(NetworkFailure('boom')));

      final container = makeContainer();
      final before =
          (await container.read(catalogControllerProvider.future)).items;
      final wasFavorite = before.firstWhere((i) => i.id == '1').isFavorite;

      await container
          .read(catalogControllerProvider.notifier)
          .toggleFavorite('1');

      final async = container.read(catalogControllerProvider);
      // Contract: guard turns the thrown Failure into AsyncError. The previous
      // value is preserved on the AsyncError, so the optimistic change is gone.
      expect(async.hasError, isTrue);
      expect(async.error, isA<NetworkFailure>());
      final preserved = async.valueOrNull?.items.firstWhere((i) => i.id == '1');
      expect(preserved?.isFavorite, wasFavorite); // rolled back, not toggled
      verify(() => repo.toggleFavorite('1')).called(1);
    });
  });

  // -------------------------------------------------------------------------
  // Pure UI mutation + guards.
  // -------------------------------------------------------------------------
  group('CatalogController — pure mutations & guards', () {
    test('setFilter changes the view without touching the repo', () async {
      when(() => repo.fetchItems()).thenAnswer((_) async => const Ok(items));

      final container = makeContainer();
      await container.read(catalogControllerProvider.future);

      container
          .read(catalogControllerProvider.notifier)
          .setFilter(CatalogFilter.favorites);

      final state = container.read(catalogControllerProvider).requireValue;
      expect(state.filter, CatalogFilter.favorites);
      expect(state.visibleItems.map((i) => i.id), ['2']); // only favorites
      verifyNever(() => repo.fetchItems()); // beyond the single build() call
    });

    test('refresh preserves the active filter across reload', () async {
      when(() => repo.fetchItems()).thenAnswer((_) async => const Ok(items));

      final container = makeContainer();
      await container.read(catalogControllerProvider.future);
      container
          .read(catalogControllerProvider.notifier)
          .setFilter(CatalogFilter.favorites);

      await container.read(catalogControllerProvider.notifier).refresh();

      final state = container.read(catalogControllerProvider).requireValue;
      expect(state.filter, CatalogFilter.favorites); // survived the refresh
      verify(() => repo.fetchItems()).called(2); // initial + refresh
    });
  });
}
