// test/features/catalog/presentation/catalog_screen_widget_test.dart
//
// GENERATED by skill 70 (Test Generation Agent) from CatalogScreen — a
// ConsumerWidget that ref.watches catalogControllerProvider and renders one of
// the four async states (skill 16) plus a refresh interaction.
//
// Method (skill 70 §"per-type: screen"): read the screen + the controller it
// watches, then assert ALL FOUR async states render and ONE key interaction.
// We override the CONTROLLER directly with stubbed AsyncValues for the pure
// state-rendering tests (fast, no async plumbing), and override the REPO for the
// interaction test so the real controller logic runs through the widget.
//
// Harness: skill 20's pumpApp (test/support/test_helpers.dart) — not re-derived
// here. Conventions: ../../../references/CONVENTIONS.md (§4 four states, §6).

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import 'package:my_app/core/error/result.dart'; // Ok, Err, NetworkFailure
import 'package:my_app/features/catalog/application/catalog_controller.dart';
import 'package:my_app/features/catalog/application/catalog_state.dart';
import 'package:my_app/features/catalog/domain/catalog_repository.dart';
import 'package:my_app/features/catalog/presentation/catalog_screen.dart';

// Shared pumpApp + fakes (skill 20). Add CatalogRepository's fake there too.
import '../../../support/test_helpers.dart';

class MockCatalogRepository extends Mock implements CatalogRepository {}

void main() {
  const loadedItems = [
    CatalogItem(id: '1', title: 'Alpha'),
    CatalogItem(id: '2', title: 'Beta', isFavorite: true),
  ];

  // Override the controller to emit a fixed AsyncValue, so a test can render a
  // single state without wiring async. `overrideWith` builds a notifier whose
  // build() returns the given state synchronously.
  Override controllerReturning(AsyncValue<CatalogState> value) {
    return catalogControllerProvider.overrideWith(
      () => _StubCatalogController(value),
    );
  }

  group('CatalogScreen — four async states (skill 16)', () {
    testWidgets('loading: shows a spinner while the controller is pending',
        (tester) async {
      // A controller stuck in AsyncLoading models the pending build.
      await tester.pumpApp(
        const CatalogScreen(),
        overrides: [controllerReturning(const AsyncLoading())],
      );

      // pump() not pumpAndSettle() — a spinner animates forever.
      expect(find.byType(CircularProgressIndicator), findsOneWidget);
      expect(find.text('Alpha'), findsNothing);
    });

    testWidgets('data: renders each item when state has content',
        (tester) async {
      await tester.pumpApp(
        const CatalogScreen(),
        overrides: [
          controllerReturning(const AsyncData(CatalogState(items: loadedItems))),
        ],
      );
      await tester.pump();

      expect(find.byType(CircularProgressIndicator), findsNothing);
      expect(find.text('Alpha'), findsOneWidget);
      expect(find.text('Beta'), findsOneWidget);
    });

    testWidgets('empty: renders the empty-state widget, not a blank screen',
        (tester) async {
      await tester.pumpApp(
        const CatalogScreen(),
        overrides: [
          controllerReturning(const AsyncData(CatalogState())), // items == []
        ],
      );
      await tester.pump();

      // The empty state is a distinct, asserted widget (find by key).
      expect(find.byKey(const Key('catalog_empty')), findsOneWidget);
      expect(find.text('Alpha'), findsNothing);
    });

    testWidgets('error: renders the error message and a retry affordance',
        (tester) async {
      await tester.pumpApp(
        const CatalogScreen(),
        overrides: [
          controllerReturning(
            AsyncError(const NetworkFailure('offline'), StackTrace.empty),
          ),
        ],
      );
      await tester.pump();

      expect(find.text('offline'), findsOneWidget);
      expect(find.byKey(const Key('catalog_retry')), findsOneWidget);
    });
  });

  group('CatalogScreen — key interaction', () {
    late MockCatalogRepository repo;

    setUpAll(() => registerFallbackValue(''));
    setUp(() => repo = MockCatalogRepository());

    testWidgets('tapping refresh re-fetches and renders the new data',
        (tester) async {
      // Real controller logic runs through the widget — override the REPO.
      when(() => repo.fetchItems())
          .thenAnswer((_) async => const Ok(loadedItems));

      await tester.pumpApp(
        const CatalogScreen(),
        overrides: [catalogRepositoryProvider.overrideWithValue(repo)],
      );
      await tester.pump(); // resolve initial load → data
      expect(find.text('Alpha'), findsOneWidget);

      // Change the backing data, then tap refresh.
      when(() => repo.fetchItems()).thenAnswer(
        (_) async => const Ok([CatalogItem(id: '3', title: 'Gamma')]),
      );
      await tester.tap(find.byKey(const Key('catalog_refresh')));
      await tester.pumpAndSettle();

      expect(find.text('Gamma'), findsOneWidget);
      expect(find.text('Alpha'), findsNothing);
      verify(() => repo.fetchItems()).called(2); // initial + refresh
    });
  });
}

/// A controller stub that emits a fixed [AsyncValue] for state-rendering tests.
/// Subclassing the generated `_$CatalogController` keeps the provider's type and
/// lets `overrideWith` inject it. Mutation methods are no-ops here — the four
/// state tests assert rendering only; the interaction test uses the real one.
class _StubCatalogController extends CatalogController {
  _StubCatalogController(this._value);
  final AsyncValue<CatalogState> _value;

  @override
  Future<CatalogState> build() async {
    // Reflect the requested state. For loading/error we never complete normally;
    // pumpApp + the override surface the AsyncValue directly to the widget.
    return _value.when(
      data: (s) => s,
      loading: () => Completer<CatalogState>().future, // stays pending
      error: (e, _) => Future<CatalogState>.error(e),
    );
  }
}
