// Type-safe asset usage examples (stage 10).
//
// Generate the Assets/FontFamily classes first:
//   dart run build_runner build --delete-conflicting-outputs
// then import the generated file (path follows flutter_gen `output:`):
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:cached_network_image/cached_network_image.dart';

// Generated by flutter_gen — never type these paths by hand.
import 'package:myapp/gen/assets.gen.dart';

/// 1) A generated raster image. `Assets.images.*` gives compile-time safety:
/// rename `logo.png` and this line stops compiling.
class LogoExample extends StatelessWidget {
  const LogoExample({super.key});

  @override
  Widget build(BuildContext context) {
    // .image() -> Image widget · .provider() -> ImageProvider · .path -> String
    return Assets.images.logo.image(width: 120, fit: BoxFit.contain);
  }
}

/// 2) An SVG via the generated `.svg()` helper, tinted to the theme rather
/// than baking a color into the file.
class MenuIcon extends StatelessWidget {
  const MenuIcon({super.key});

  @override
  Widget build(BuildContext context) {
    return Assets.icons.menu.svg(
      width: 24,
      height: 24,
      colorFilter: ColorFilter.mode(
        Theme.of(context).colorScheme.onSurface,
        BlendMode.srcIn,
      ),
    );
  }
}

// You can also load an SVG by path when not generated:
//   SvgPicture.asset(Assets.icons.menu.path, width: 24);

/// 3) A remote image with disk caching + the four async states.
/// Loading/error widgets follow skill 16 (Loading_States) patterns —
/// swap `_ShimmerBox` for your shared shimmer/skeleton from core/widgets.
class ProductThumb extends StatelessWidget {
  const ProductThumb({required this.imageUrl, super.key});

  final String imageUrl;

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
      imageUrl: imageUrl,
      fit: BoxFit.cover,
      fadeInDuration: const Duration(milliseconds: 200),
      placeholder: (context, url) => const _ShimmerBox(), // skill 16: loading
      errorWidget: (context, url, error) =>
          const Icon(Icons.broken_image_outlined), // skill 16: error
    );
  }
}

/// 4) Precache above-the-fold local images so they paint without a flash.
/// `precacheImage` must run with a valid context (didChangeDependencies).
class SplashHeader extends StatefulWidget {
  const SplashHeader({super.key});

  @override
  State<SplashHeader> createState() => _SplashHeaderState();
}

class _SplashHeaderState extends State<SplashHeader> {
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    precacheImage(Assets.images.logo.provider(), context);
  }

  @override
  Widget build(BuildContext context) => Assets.images.logo.image(width: 160);
}

/// Minimal placeholder stand-in (use your real shimmer from skill 16).
class _ShimmerBox extends StatelessWidget {
  const _ShimmerBox();

  @override
  Widget build(BuildContext context) => ColoredBox(
        color: Theme.of(context).colorScheme.surfaceContainerHighest,
        child: const SizedBox.expand(),
      );
}
