// localization_usage.dart — reading strings + switching locale (intl + Riverpod).
//
// House style: ../../references/CONVENTIONS.md
//   §4 never hardcode strings · §6 Riverpod state (no BuildContext in notifiers,
//   no side effects/logic in build).
//
// Generated by `flutter gen-l10n` from lib/l10n/*.arb (see l10n.yaml). Import path
// depends on synthetic-package in l10n.yaml; the synthetic default is:
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:flutter_gen/gen_l10n/app_localizations.dart';

part 'localization_usage.g.dart';

// ---------------------------------------------------------------------------
// 1. Locale controller — app-lived (keepAlive) state, persisted to prefs.
//    `null` means "follow the device locale".
// ---------------------------------------------------------------------------
@Riverpod(keepAlive: true)
class LocaleController extends _$LocaleController {
  static const _prefsKey = 'app_locale';

  @override
  Locale? build() {
    // Load the persisted choice synchronously-ish; for a real app prefer an
    // AsyncNotifier or hydrate in main() before runApp. Kept simple here.
    final code = _prefs?.getString(_prefsKey);
    return code == null ? null : Locale(code);
  }

  SharedPreferences? get _prefs => ref.read(sharedPreferencesProvider).valueOrNull;

  Future<void> setLocale(Locale? locale) async {
    state = locale;
    final prefs = await ref.read(sharedPreferencesProvider.future);
    if (locale == null) {
      await prefs.remove(_prefsKey);
    } else {
      await prefs.setString(_prefsKey, locale.languageCode);
    }
  }
}

@Riverpod(keepAlive: true)
Future<SharedPreferences> sharedPreferences(Ref ref) =>
    SharedPreferences.getInstance();

// ---------------------------------------------------------------------------
// 2. Wire localizations + the active locale into MaterialApp.
// ---------------------------------------------------------------------------
class App extends ConsumerWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final locale = ref.watch(localeControllerProvider); // Locale? (null = system)
    return MaterialApp(
      onGenerateTitle: (context) => AppLocalizations.of(context)!.appTitle,
      locale: locale,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      home: const HomeScreen(),
    );
  }
}

// ---------------------------------------------------------------------------
// 3. Read strings: alias l10n once, use keys — incl. a plural & a placeholder.
// ---------------------------------------------------------------------------
class HomeScreen extends ConsumerWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = AppLocalizations.of(context)!; // alias for readability
    final cartCount = 3;

    return Scaffold(
      appBar: AppBar(title: Text(l10n.appTitle)),
      body: Padding(
        // Direction-aware padding — mirrors automatically in RTL locales.
        padding: const EdgeInsetsDirectional.only(start: 16, top: 16, end: 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(l10n.greeting('Sam')),               // placeholder
            Text(l10n.cartItemCount(cartCount)),       // ICU plural
            const SizedBox(height: 24),
            FilledButton(
              onPressed: () {
                // Side effect (changing locale) lives in a callback → ref.read.
                ref.read(localeControllerProvider.notifier).setLocale(
                      const Locale('ar'), // switch to Arabic (RTL)
                    );
              },
              child: Text(l10n.primaryCtaLabel),
            ),
          ],
        ),
      ),
    );
  }
}
