#!/usr/bin/env python3
"""Minimal OpenAPI -> Dart freezed DTO generator (Python 3 stdlib only).

Reads an OpenAPI 3 / Swagger 2 JSON document and emits one `@freezed`
`json_serializable` DTO class per entry in `components/schemas` (Swagger 2:
`definitions`) to stdout, matching the flutter-android house style (skill 49).

This is intentionally lightweight: it produces the DTO layer (the most tedious
part to hand-write). Data sources and repositories are added from the skill's
templates/. For large specs, prefer `swagger_dart_code_generator` or
`openapi-generator` (see SKILL.md).

Usage:
    python3 gen_openapi.py api/openapi.json > lib/data/dto/api_dtos.dart
    python3 gen_openapi.py api/openapi.json --part api_dtos > out.dart

Limitations (by design): no allOf/oneOf composition, no inline nested object
schemas (referenced `$ref`s and primitives/arrays/enums are handled), no request
vs response distinction. Review the output before committing.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Any

HEADER = """\
// GENERATED by skill 49 gen_openapi.py from {source}.
// Do NOT hand-edit: changes are lost on regeneration. Change the spec and re-run.
//
// ignore_for_file: type=lint
import 'package:freezed_annotation/freezed_annotation.dart';

part '{part}.freezed.dart';
part '{part}.g.dart';
"""


def fail(msg: str) -> "None":
    print(f"gen_openapi: error: {msg}", file=sys.stderr)
    sys.exit(1)


def to_pascal_case(name: str) -> str:
    """`user_profile` / `user-profile` / `User Profile` -> `UserProfile`."""
    parts = re.split(r"[^0-9a-zA-Z]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def to_camel_case(name: str) -> str:
    pascal = to_pascal_case(name)
    return pascal[:1].lower() + pascal[1:] if pascal else name


# Dart reserved words that can't be bare identifiers; suffixed with `_` if hit.
DART_RESERVED = {
    "abstract", "else", "import", "show", "as", "enum", "in", "static",
    "assert", "export", "interface", "super", "async", "extends", "is",
    "switch", "await", "extension", "library", "sync", "break", "external",
    "mixin", "this", "case", "factory", "new", "throw", "catch", "false",
    "null", "true", "class", "final", "on", "try", "const", "finally",
    "operator", "typedef", "continue", "for", "part", "var", "covariant",
    "function", "rethrow", "void", "default", "get", "return", "while",
    "deferred", "hide", "set", "with", "do", "if", "yield", "dynamic",
    "implements", "while",
}


def schemas_of(doc: dict[str, Any]) -> dict[str, Any]:
    """Return the schema map for OpenAPI 3 or Swagger 2."""
    comp = doc.get("components")
    if isinstance(comp, dict) and isinstance(comp.get("schemas"), dict):
        return comp["schemas"]
    if isinstance(doc.get("definitions"), dict):  # Swagger 2
        return doc["definitions"]
    return {}


def ref_name(ref: str) -> str:
    """`#/components/schemas/User` -> `User`."""
    return ref.rsplit("/", 1)[-1]


def dart_type(schema: dict[str, Any]) -> str:
    """Map an OpenAPI property schema to a (non-nullable) Dart type."""
    if not isinstance(schema, dict):
        return "dynamic"
    if "$ref" in schema:
        return to_pascal_case(ref_name(schema["$ref"])) + "Dto"

    fmt = schema.get("format")
    typ = schema.get("type")

    # OpenAPI 3.1 may express type as a list (e.g. ["string", "null"]).
    if isinstance(typ, list):
        typ = next((t for t in typ if t != "null"), None)

    if typ == "array":
        items = schema.get("items", {})
        return f"List<{dart_type(items)}>"
    if typ == "object" or typ is None:
        return "Map<String, dynamic>"
    if typ == "integer":
        return "int"
    if typ == "number":
        return "double"
    if typ == "boolean":
        return "bool"
    if typ == "string":
        if fmt in ("date-time", "date"):
            return "DateTime"
        return "String"
    return "dynamic"


def default_literal(value: Any) -> str | None:
    """Render an OpenAPI `default` as a Dart literal for `@Default(...)`."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    return None


def field_line(prop: str, schema: dict[str, Any], required: bool) -> str:
    """Build one DTO factory parameter line."""
    dart = dart_type(schema)
    camel = to_camel_case(prop)
    if camel in DART_RESERVED:
        camel = camel + "_"

    annotations: list[str] = []
    if camel != prop or (camel + "_" == prop):
        annotations.append(f"@JsonKey(name: '{prop}')")

    has_default = "default" in schema
    default_lit = default_literal(schema.get("default")) if has_default else None

    if has_default and default_lit is not None:
        annotations.append(f"@Default({default_lit})")
        type_str = dart  # has a default -> effectively non-null
    elif required:
        type_str = f"required {dart}"
    else:
        type_str = f"{dart}?"  # optional, no default -> nullable

    prefix = (" ".join(annotations) + " ") if annotations else ""
    return f"    {prefix}{type_str} {camel},"


def render_dto(name: str, schema: dict[str, Any]) -> str:
    cls = to_pascal_case(name) + "Dto"
    props = schema.get("properties")
    if not isinstance(props, dict):
        props = {}
    required = set(schema.get("required", []) or [])

    lines: list[str] = []
    lines.append(f"/// Generated DTO for the OpenAPI `{name}` schema.")
    lines.append("///")
    lines.append("/// Lives in `data/` — the only type that knows JSON. Map to a")
    lines.append("/// domain entity via [toEntity] (hand-owned). The domain never")
    lines.append("/// imports this type (CONVENTIONS §2).")
    lines.append("@freezed")
    lines.append(f"class {cls} with _${cls} {{")
    lines.append(f"  /// Creates a [{cls}].")
    if props:
        lines.append(f"  const factory {cls}({{")
        for prop, pschema in props.items():
            ps = pschema if isinstance(pschema, dict) else {}
            lines.append(field_line(prop, ps, prop in required))
        lines.append(f"  }}) = _{cls};")
    else:
        # Schema with no properties: emit an empty factory so it still compiles.
        lines.append(f"  const factory {cls}() = _{cls};")
    lines.append("")
    lines.append(f"  const {cls}._();")
    lines.append("")
    lines.append(f"  /// Deserializes a [{cls}] from a decoded JSON map.")
    lines.append(
        f"  factory {cls}.fromJson(Map<String, dynamic> json) =>"
    )
    lines.append(f"      _${cls}FromJson(json);")
    lines.append("")
    lines.append("  /// Maps this transport DTO to its domain entity (stub).")
    lines.append("  ///")
    lines.append("  /// The generator cannot know your domain model; fill this in")
    lines.append("  /// to return the hand-owned entity from `domain/`.")
    lines.append("  // TODO(skill-49): return the real domain entity.")
    lines.append("  Object toEntity() => this;")
    lines.append("}")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Dart freezed DTOs from an OpenAPI JSON spec.",
    )
    parser.add_argument("spec", help="Path to the OpenAPI/Swagger JSON file.")
    parser.add_argument(
        "--part",
        default="api_dtos",
        help="Basename for the freezed/json `part` directives "
        "(must match the output filename without .dart). Default: api_dtos.",
    )
    args = parser.parse_args(argv)

    try:
        with open(args.spec, "r", encoding="utf-8") as fh:
            doc = json.load(fh)
    except FileNotFoundError:
        return fail(f"spec not found: {args.spec}") or 1
    except json.JSONDecodeError as exc:
        return fail(f"spec is not valid JSON ({exc}). YAML is not supported — "
                    "convert to JSON first.") or 1

    if not isinstance(doc, dict):
        return fail("top-level spec must be a JSON object") or 1

    schemas = schemas_of(doc)
    if not schemas:
        return fail("no schemas found under components/schemas (OpenAPI 3) or "
                    "definitions (Swagger 2)") or 1

    out: list[str] = [HEADER.format(source=args.spec, part=args.part)]
    for name, schema in schemas.items():
        if not isinstance(schema, dict):
            continue
        # Skip enum-only or pure-scalar schemas: freezed DTOs need an object.
        if schema.get("type") not in (None, "object") and "properties" not in schema:
            print(f"gen_openapi: skipping non-object schema '{name}'",
                  file=sys.stderr)
            continue
        out.append(render_dto(name, schema))

    sys.stdout.write("\n\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
