// GENERATED by skill 49 (OpenAPI → Dart) for the `users` tag, then committed.
// Data sources are regenerated from the spec; keep custom logic in the
// repository or the domain entity, not here.
//
// Tag: users
// Operations: getUsers (GET /users), getUserById (GET /users/{id}),
//             createUser (POST /users)
import 'package:dio/dio.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'generated_dto.example.dart';

// The shared, configured client lives in `lib/core/network/dio_client.dart`
// (skill 11). Its auth interceptor (skill 13) attaches the bearer token derived
// from the spec's `securitySchemes` — the generator never puts tokens in code.
//   import 'package:<app>/core/network/dio_client.dart'; // dioProvider

part 'generated_data_source.example.g.dart';

/// Talks to the network for the `users` tag.
///
/// Each method mirrors one OpenAPI operation, sends/receives only DTOs, and
/// **lets `DioException`s propagate** — it never catches. The repository is the
/// boundary that maps those exceptions to a `Failure` (skill 15); see
/// `generated_repository.example.dart`.
class UsersRemoteDataSource {
  /// Creates a [UsersRemoteDataSource] from the shared, configured [Dio].
  const UsersRemoteDataSource(this._dio);

  final Dio _dio;

  /// `getUsers` — GET `/users`. Lists users, optionally filtered/paged.
  Future<List<UserDto>> getUsers({int? page, int? perPage}) async {
    final response = await _dio.get<List<dynamic>>(
      '/users',
      queryParameters: <String, dynamic>{
        if (page != null) 'page': page,
        if (perPage != null) 'per_page': perPage,
      },
    );
    final data = response.data ?? const <dynamic>[];
    return data.cast<Map<String, dynamic>>().map(UserDto.fromJson).toList();
  }

  /// `getUserById` — GET `/users/{id}`. Fetches one user.
  Future<UserDto> getUserById(String id) async {
    final response = await _dio.get<Map<String, dynamic>>('/users/$id');
    final data = response.data;
    if (data == null) {
      // Empty body where the spec promised a User: a transport problem. Surface
      // it as a DioException so the repository maps it like any other failure.
      throw DioException(
        requestOptions: response.requestOptions,
        response: response,
        type: DioExceptionType.badResponse,
        error: 'Empty body for GET /users/$id',
      );
    }
    return UserDto.fromJson(data);
  }

  /// `createUser` — POST `/users`. Sends a request DTO, returns the created one.
  Future<UserDto> createUser(UserDto body) async {
    final response = await _dio.post<Map<String, dynamic>>(
      '/users',
      data: body.toJson(),
    );
    final data = response.data;
    if (data == null) {
      throw DioException(
        requestOptions: response.requestOptions,
        response: response,
        type: DioExceptionType.badResponse,
        error: 'Empty body for POST /users',
      );
    }
    return UserDto.fromJson(data);
  }
}

/// Provides the [UsersRemoteDataSource], wired to the shared `dioProvider`.
@riverpod
UsersRemoteDataSource usersRemoteDataSource(Ref ref) =>
    // Once core/network/dio_client.dart is in place:
    //   UsersRemoteDataSource(ref.watch(dioProvider));
    UsersRemoteDataSource(ref.watch(dioProvider));
