// GENERATED by skill 49 (OpenAPI → Dart) for the `users` tag, then committed.
// The repository is the boundary where transport errors stop: it catches, maps
// to `Failure` (skill 15), maps DTO → domain entity, and returns `Result<T>`.
import 'package:dio/dio.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'generated_data_source.example.dart';
import 'generated_dto.example.dart';

// The error contract is owned by skill 15 in `lib/core/error/`. In a real app,
// delete the placeholder section at the bottom and import:
//   import 'package:<app>/core/error/result.dart';        // Result, Ok, Err
//   import 'package:<app>/core/error/error_mapper.dart';  // mapError
// The domain repository interface is hand-owned in the feature's `domain/`:
//   import 'package:<app>/features/user/domain/user_repository.dart';

part 'generated_repository.example.g.dart';

/// Concrete [UserRepository] for the `users` tag.
///
/// Every method calls the generated data source inside `try/catch`, maps any
/// exception to a `Failure` via skill 15's `mapError`, maps the DTO to its
/// domain entity with `toEntity()`, and returns `Result<T>` — never throwing
/// across the layer line (CONVENTIONS §5).
final class UserRepositoryImpl implements UserRepository {
  /// Creates a [UserRepositoryImpl].
  const UserRepositoryImpl(this._remote);

  final UsersRemoteDataSource _remote;

  @override
  Future<Result<List<UserEntity>>> getUsers({int? page, int? perPage}) async {
    try {
      final dtos = await _remote.getUsers(page: page, perPage: perPage);
      return Ok(dtos.map((d) => d.toEntity()).toList());
    } on DioException catch (e, st) {
      return Err(mapError(e, st));
    } on Object catch (e, st) {
      return Err(mapError(e, st));
    }
  }

  @override
  Future<Result<UserEntity>> getUser(String id) async {
    try {
      final dto = await _remote.getUserById(id);
      return Ok(dto.toEntity());
    } on DioException catch (e, st) {
      return Err(mapError(e, st));
    } on Object catch (e, st) {
      return Err(mapError(e, st));
    }
  }

  @override
  Future<Result<UserEntity>> createUser(UserEntity user) async {
    try {
      // Map domain → DTO for the request body, then DTO → domain for the result.
      final body = UserDto(id: user.id, email: user.email);
      final dto = await _remote.createUser(body);
      return Ok(dto.toEntity());
    } on DioException catch (e, st) {
      return Err(mapError(e, st));
    } on Object catch (e, st) {
      return Err(mapError(e, st));
    }
  }
}

/// Binds the domain [UserRepository] interface to its implementation.
///
/// Downstream code depends on the *interface* type, so tests override this (or
/// `dioProvider`) with a fake via `ProviderScope(overrides:)` — DI chain is
/// dio → data source → repository (skill 11).
@riverpod
UserRepository userRepository(Ref ref) =>
    UserRepositoryImpl(ref.watch(usersRemoteDataSourceProvider));

// ---------------------------------------------------------------------------
// PLACEHOLDERS — owned by skill 15 (core/error) and the feature's domain layer.
// Delete this section and import the real types once those stages land; they
// are inlined here only so this template compiles and demonstrates the flow.
// ---------------------------------------------------------------------------

/// Domain contract for the `users` feature (normally in `domain/`).
abstract interface class UserRepository {
  /// Lists users.
  Future<Result<List<UserEntity>>> getUsers({int? page, int? perPage});

  /// Loads one user by id.
  Future<Result<UserEntity>> getUser(String id);

  /// Creates a user, returning the persisted entity.
  Future<Result<UserEntity>> createUser(UserEntity user);
}

/// Outcome wrapper — see CONVENTIONS §5. Owned by skill 15.
sealed class Result<T> {
  const Result();
}

/// Success carrying a [value].
final class Ok<T> extends Result<T> {
  /// Creates an [Ok].
  const Ok(this.value);

  /// The successful value.
  final T value;
}

/// Failure carrying a typed [failure].
final class Err<T> extends Result<T> {
  /// Creates an [Err].
  const Err(this.failure);

  /// The mapped failure.
  final Failure failure;
}

/// Typed failure base — owned by skill 15.
sealed class Failure {
  /// Creates a [Failure].
  const Failure(this.message);

  /// Developer-facing message (logs only).
  final String message;
}

/// Fallback failure used by the placeholder mapper below.
final class UnknownFailure extends Failure {
  /// Creates an [UnknownFailure].
  const UnknownFailure(super.message);
}

/// Placeholder for skill 15's `mapError`.
///
/// The real mapper translates `DioException` types into the right `Failure`
/// (timeout → `TimeoutFailure`, 401/403 → `UnauthorizedFailure`,
/// 404 → `NotFoundFailure`, no connection → `NetworkFailure`, …).
Failure mapError(Object error, StackTrace stackTrace) =>
    UnknownFailure(error.toString());
