// GENERATED by skill 49 (OpenAPI → Dart). Reviewed, then committed.
// Do NOT hand-edit: changes are lost on regeneration. To change a field, change
// the spec (api/openapi.json) and re-run scripts/gen_openapi.py.
//
// Source schema: components/schemas/User
import 'package:freezed_annotation/freezed_annotation.dart';

// In a real feature the domain entity is hand-owned and lives in `domain/`:
//   import 'package:<app>/features/user/domain/user_entity.dart';
// The generator emits the stub at the bottom of this file so it compiles alone.

part 'generated_dto.example.freezed.dart';
part 'generated_dto.example.g.dart';

/// Wire model generated from the OpenAPI `User` schema.
///
/// Lives in `data/dto/` and is the *only* type that knows JSON. Data sources
/// return these; the repository maps them to the domain entity via [toEntity]
/// (the domain never imports this type — CONVENTIONS §2 dependency rule).
///
/// Field mapping rules the generator applied:
/// - `required: [id, email]` → non-nullable Dart fields.
/// - optional `display_name` → nullable `String?`.
/// - optional `is_active` with `default: true` → `@Default(true)`.
/// - snake_case wire names → camelCase Dart with `@JsonKey(name: ...)`.
@freezed
class UserDto with _$UserDto {
  /// Creates a [UserDto].
  const factory UserDto({
    required String id,
    required String email,
    @JsonKey(name: 'display_name') String? displayName,
    @JsonKey(name: 'avatar_url') String? avatarUrl,
    @JsonKey(name: 'is_active') @Default(true) bool isActive,
    @JsonKey(name: 'created_at') DateTime? createdAt,
  }) = _UserDto;

  const UserDto._();

  /// Deserializes a [UserDto] from a decoded JSON map.
  factory UserDto.fromJson(Map<String, dynamic> json) =>
      _$UserDtoFromJson(json);

  /// Maps this transport DTO to its pure domain entity.
  ///
  /// Generated as a stub. The domain entity is hand-owned — adjust this mapping
  /// (e.g. derive `name` from `displayName ?? email`) and keep it where the
  /// real `UserEntity` is defined.
  UserEntity toEntity() => UserEntity(
        id: id,
        email: email,
        name: displayName ?? email,
        isActive: isActive,
      );
}

// ---------------------------------------------------------------------------
// PLACEHOLDER domain entity — hand-owned in `domain/user_entity.dart`.
// The generator emits this stub only so the DTO compiles standalone; in a real
// feature this file imports the entity instead of declaring it.
// ---------------------------------------------------------------------------

/// Pure domain entity for a user (normally a `freezed` entity in `domain/`).
class UserEntity {
  /// Creates a [UserEntity].
  const UserEntity({
    required this.id,
    required this.email,
    required this.name,
    required this.isActive,
  });

  /// Stable identifier.
  final String id;

  /// Login email.
  final String email;

  /// Display name (falls back to email when unset).
  final String name;

  /// Whether the account is active.
  final bool isActive;
}
